### ISSUE TITLE
Creating a portfolio with a duplicate name error is not catchable. 

### ISSUE THREAD

**Issue by po0uyan** [PolymeshAssociation/polymesh-sdk#1116] opened 2024-01-12 13:38 UTC
Hi, let's consider the following is creating a portfolio which is already there. 
```TS 
try {
      identity?.portfolios.getPortfolio
      const port = await api.identities.createPortfolio({ name: "test" });
      const ress = await port.run();
    } catch (e) {
      console.log("there was an error" + e);
    }
```
What I expect from this block of code is that If it fails for any reason including a duplicate portfolio name, It would be catchable inside that catch block. But it fails with the following error and doesn't end up in catch block: 
```
throw new internal_1.PolymeshError({
                ^
PolymeshError: There already exist Portfolios with some of the given names
    at Procedure.<anonymous>
```
can you please guide me through the correct way of handling this?

**Comment by polymath-eric** [comment] 2024-01-12 14:01
Hi @po0uyan, thanks for bringing this to our attention.

The SDK was designed on a previous version of node, where unhandled promises did not crash the process.

This is something we will look into solving more correctly soon, but in the meantime you can use `--unhandled-rejections=none` as an option for node, or register a handler on the process itself so that the error becomes catchable.

```ts
process.on('unhandledRejection', reason => {
  console.warn(`unhandled rejection, reason: ${reason}`);
});
```

We will be looking into a solution where this isn't needed, but hopefully this works for you in the meantime.

**Comment by po0uyan** [comment] 2024-01-12 14:07
Great thanks.

**Comment by monitz87** [comment] 2024-01-14 00:18
> Hi @po0uyan, thanks for bringing this to our attention.
> 
> The SDK was designed on a previous version of node, where unhandled promises did not crash the process.
> 
> This is something we will look into solving more correctly soon, but in the meantime you can use `--unhandled-rejections=none` as an option for node, or register a handler on the process itself so that the error becomes catchable.
> 
> ```ts
> process.on('unhandledRejection', reason => {
>   console.warn(`unhandled rejection, reason: ${reason}`);
> });
> ```
> 
> We will be looking into a solution where this isn't needed, but hopefully this works for you in the meantime.

You can use `defusePromise` from the internal utils when calling `prepareTransactions` in the Procedure's `prepare` method to get around the issue. It's ugly, but it was made for this specific scenario.

```ts
const prepareTransactionsPromise = defusePromise(this.prepareTransactions(procArgs));
```

Should be safe since the promise is being handled later on anyway

P.S.: Hi :D

**Comment by po0uyan** [comment] 2024-01-17 19:42
> ```ts
> unhandledRejection
> ```

Thanks @monitz87 , is this available on polymesh too ? can you elaborate more on how can I implement this in create portfolio example?

**Comment by monitz87** [comment] 2024-01-21 18:56
@po0uyan no, sorry for the misunderstanding. My comment was referring to how the bug can be fixed in the SDK code, not to how it can be sidestepped in userland

**Comment by polymath-eric** [comment] 2024-03-08 19:37
@monitz87 Thanks, that seems to resolve the issue!

Sorry for the late reply, I missed the notification you replied.

We've been busy working on the zero knowledge "polymesh-private" stuff which is wrapping up. I figured I would finally have time to tackle this only to find you posted the fix like 6 weeks ago.

I hope things are going well for you!

**Closed** 2024-03-11 14:15 UTC
Labels: released on @alpha

**Comment by polymath-eric** [comment] 2024-03-11 14:18
@po0uyan You should be able to use the alpha release: `24.0.0-alpha.15` which resolves this issue.

It will get merged into beta and master at a later date.
